# Generated by Django 5.2.7 on 2025-11-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='join_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
