# Generated by Django 5.2.7 on 2025-11-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_student_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=0),
        ),
    ]
