# Generated by Django 5.2.7 on 2025-11-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_course_rename_author_book_author_student_ourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_ourse',
            new_name='StudentCourse',
        ),
    ]
