# Generated by Django 5.2.7 on 2025-11-29 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_company_schedule_slot_visitors_remove_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='curent_user',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='slot',
        ),
        migrations.AddField(
            model_name='slot',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.schedule'),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(blank=True, choices=[('booked', 'Booked'), ('open', 'Open')], default='open', max_length=10),
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
