# Generated by Django 5.2.7 on 2025-11-30 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_visitors_slot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.company'),
        ),
    ]
